### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Latios1** [CreaturePhil/Showdown-Boilerplate#134]
Can you update the repo? They have done a chat refactor, then emoticons don't work(sorry for my english)

**Comment by CreaturePhil** [comment]
@Latios1 Just updated. Try it now.

**Comment by Latios1** [comment]
How did you fix [this ](http://image.prntscr.com/image/ffd7e35ccda1459ab9f1a97d8b44f1c1.png)error?(I had sent a "feelsgd" in lobby)

**Comment by CreaturePhil** [comment]
Are you using the latest Showdown-Boilerplate?

**Comment by Lord-Haji** [comment]
@CreaturePhil u did delete chat.js how will the server run now ?

**Comment by TheFenderStory** [comment]
He didn't
