### ISSUE TITLE
Problems with deprecated Tools.escapeHTML

### ISSUE THREAD

**Issue by CreaturePhil** [CreaturePhil/Showdown-Boilerplate#135]
Rambo: while doing &#x2f;profile it says Tool.escape.HTML is not defined and while doing &#x2f;atm it crashes

**Comment by HoeenCoder** [comment]
@CreaturePhil the escapeHTML function is no longer under Tools, its now under Chat 

`Chat.escapeHTML()`

**Comment by rambo199** [comment]
Yea i replaced that in all the files with Chat.escapeHTML and created the pull request.
