### ISSUE TITLE
How do I add custom Pokemon?

### ISSUE THREAD

**Issue by Ericpro06** [CreaturePhil/Showdown-Boilerplate#140]
Hi, is it possible to add custom Pokemon?

**Comment by HoeenCoder** [comment]
No you would need a custom client to handle things such as the pokemon's image.

See [the Pokemon Showdown Client](https://github.com/Zarel/Pokemon-Showdown-Client) for that.

Server side you would need to add data for the pokemon (in a mod you create).
Also before anyone asks, no i'm not interested in helping make custom pokemon.

**Comment by TheFenderStory** [comment]
what if we replaced mons we don't care about (CAP for example) with our fakemons and used CSS to replace the images 0_0

**Comment by HoeenCoder** [comment]
Thats... actually not a bad idea @TheFenderStory 0_0
