### ISSUE TITLE
List with commands

### ISSUE THREAD

**Issue by DaniellMesquita** [CreaturePhil/Showdown-Boilerplate#54]
Will be nice add a list in .MD containing all /commands that can be used in chat.

**Comment by TheFenderStory** [comment]
I've been meaning to write something like this for Origin. I'll take care of it.

**Comment by CreaturePhil** [comment]
Merge in https://github.com/CreaturePhil/Showdown-Boilerplate/commit/30ec20b291201d945ff8b02bce56f0fcc6dd2dd4
