### ISSUE TITLE
[SUGGESTION] Multi-language system

### ISSUE THREAD

**Issue by DaniellMesquita** [CreaturePhil/Showdown-Boilerplate#59]
.json files with all phrases, and display language strings accourding to user's language.

**Comment by CreaturePhil** [comment]
Can you give an example json for any language

**Comment by TheFenderStory** [comment]
I can create a list of all the strings we send in the custom files at least, however i'll need someone to translate them for me. (Google translate can only take me so far)

**Comment by DaniellMesquita** [comment]
I can translate to brazillian portuguese and spañol! :D

**Comment by AustinXII** [comment]
The amount of use this would have is far too low to actually bother implementing this, if you want a translated version you would have to do it yourself to whatever language you prefer. @DaniellMesquita

**Comment by DaniellMesquita** [comment]
@AustinXII, you is bothering all my issues, ONLY YOU. Issues isn't the place for fights, BUT YOU AN GIRL FOR YOU IS THE REALLY TRASH ISSUE THAT I NEED OPEN!!!!

**Comment by TheFenderStory** [comment]
Umm @CreaturePhil

**Comment by AustinXII** [comment]
I agree @DaniellMesquita but sadly this isn't an issue and shouldn't have been opened in the first place :/

**Comment by DaniellMesquita** [comment]
@AustinXII I don't need an translated version because I know how translate to portuguese for my server. What servers need is an language system for those want make an multilangual server. This is based on the concept of globalization. While GitHub don't make an section for suggestions, the issues section is the best place, in my opinion.

**Comment by TheFenderStory** [comment]
I don't disagree that a multilingual system would be a good idea, i just feel that you could write up a pull request and submit it instead of expecting the rest of us to do it for you :P

**Comment by DaniellMesquita** [comment]
@AustinXII I don't need an translated version because I know how translate to portuguese for my server. What servers need is an language system for those want make an multilangual server. This is based on the concept of globalization. While GitHub don't make an section for suggestions, the issues section is the best place, in my opinion.

**Comment by DaniellMesquita** [comment]
@TheFenderStory I have other ocupations, and i left some works to do this suggestion that is benefical for your team and some servers that need this feature, like Pandora, Origin, Big Bang, Indigo, Brasil, etc.

**Comment by AustinXII** [comment]
@DaniellMesquita as I said before, there isn't enough people for that to be a relevant issue, if we translated all of the commands and stuff it would only be a hassle for us that no one would really use. In other words, too much work for little relevance anywhere. Also I think pm'ing CreaturePhil on PS would be a better place for suggestions. The issues portion of github should be used for Issues not suggestions

**Comment by DaniellMesquita** [comment]
@AustinXII not the comands, but the other phrases. Ok, I will PM CreaturePhil while GitHub don't implement an suggestion system. The disvantage of pm'ing CreaturePhil is that he can reject wihout an forum discution.

**Comment by AustinXII** [comment]
@DaniellMesquita he could do that here as well lol

**Comment by CreaturePhil** [comment]
You can make an issue to suggest a feature for this repo. I don't mind.
I like the idea of globalization and multilingual server. An example implentation is to put into a **languages/** folder with files of each language like ``portuguese.json`` or `chinese.json`.

Here is an example file:

```json
// spanish.json
{
  "authority": ["autoridad", "authmundial", "listapersonal"],
  "help": ["Ayuda"]
}
```

**Comment by DaniellMesquita** [comment]
@CreaturePhil very good! Thanks for accept and understand my suggestions. But I think that ''pt-BR.json'' | ''pt-PT.json'' formats are better.

**Comment by CreaturePhil** [comment]
@DaniellMesquita What does that stand for?

**Comment by DaniellMesquita** [comment]
This is an more standarized name for language jsons and more near to different phrases of different countryes that speak the same language. The Brasil portuguese is different of Portugal portuguese, as example. I have friends that can translate to pt-PT, and I can translate to pt-BR and spanish.

**Comment by CreaturePhil** [comment]
@DaniellMesquita Cool, just translate pr-BR as the first one for now as an example. When you have time, make a pr please. :+1:

**Comment by DaniellMesquita** [comment]
I've openned in #66. Can U accept because I have other pull to send?
