### ISSUE TITLE
Avatars issue isn't fully fixed

### ISSUE THREAD

**Issue by DaniellMesquita** [CreaturePhil/Showdown-Boilerplate#60]
http://prntscr.com/96axwz
I can't do this. Please, remove the "/" that appear after the URL.

**Comment by TheFenderStory** [comment]
"http://address:port/avatars/user.png"  should be the proper format to display customavatars in profile. @CreaturePhil what would cause this to not work? Incorrect address?

**Comment by DaniellMesquita** [comment]
@TheFenderStory the function is retrieving "/" after URL. Please program to remove this to use this format: http://address:port/avatars/user.png
and will work properly.

**Comment by TheFenderStory** [comment]
Oh i see what's causing your issue. I'm not entirely sure we can can write code to omit the "/" in the url. 
When you specify the server url in config: `exports.avatarurl = ' ';` make sure you omit the "/". We call avatarurl in profile here: `this.url = Config.avatarurl || '';` So the solution is just fixing it in config.js

**Comment by DaniellMesquita** [comment]
You have fixed this?

**Comment by AustinXII** [comment]
@DaniellMesquita this is an issue on your end, make sure you didn't put ``server.psim.us/`` when making your avatar config

**Comment by DaniellMesquita** [comment]
@AustinXII This is an real issue and isn't an problem only with me. Please only post relevant comments.

**Comment by AustinXII** [comment]
@DaniellMesquita do you have any proof at all that this is happening to other people? with all the servers that I have ever used from this we have never had this problem

**Comment by DaniellMesquita** [comment]
@AustinXII, why the "/" after URLs in avatars can happening only with me? Please, only post relevant and construtive comments.²

**Comment by DaniellMesquita** [comment]
@TheFenderStory the solution is quite simple. By specifying the server URL in exports.avatarurl. I will make a tutorial for new users to how completly set up a server in an .MD file.
The problem is for people thatt not specified the server URL in eexports.avatarurl, then the script gets automatically the URL, then causes the problem: the taked URL has an "/" after.

**Comment by DaniellMesquita** [comment]
Update: I've set the server URL in exports.avatarurl, and this continues with issues. The solution using the [IP].psim.us as server URL.
