### ISSUE TITLE
Remove duplications in tour battle anounces

### ISSUE THREAD

**Issue by DaniellMesquita** [CreaturePhil/Showdown-Boilerplate#62]
http://prntscr.com/96spev
Please, maintain the bold names with colors, but remove the tier message, please only show "Tournament battle".

**Comment by TheFenderStory** [comment]
This occurs since you have report battles set to true in config. We'd probably have to modify some native files to change this. Maybe something you could do on your own server.

**Comment by DaniellMesquita** [comment]
The problem isn't report battles, but the irrelevant duplication/redundance IN TOUR BATTLES.

**Comment by TheFenderStory** [comment]
Right I understand that, however tours report battles because battle reporting isn't enabled on all servers . Perhaps I'll see about writing some code to change tour battle reporting when  battle reporting is enabled

**Comment by DaniellMesquita** [comment]
Yes, People already know the tier of tour, then is irrelevant report as an common battle, but yes as an tour battle with one message. Oh, please keep the colors in usernames :3

**Comment by AustinXII** [comment]
This is really more of an annoyance than a feature we should bother fixing.
