### ISSUE TITLE
Can set timer to tour

### ISSUE THREAD

**Issue by DaniellMesquita** [CreaturePhil/Showdown-Boilerplate#64]
Can set the time left for tour start.

**Comment by TheFenderStory** [comment]
Can you clarify what you mean by this?

**Comment by DaniellMesquita** [comment]
Set a timer for tour begin (start) automatically.

**Comment by AustinXII** [comment]
you already opened this issue on main and I told you there this was already a thing, is there a reason you have to open another issue here 2 days later? To clarify to make a tournament automatically start type in ``/tour setautostart [time]``
