### ISSUE TITLE
Avatar exibition in profile don't work for offline users

### ISSUE THREAD

**Issue by DaniellMesquita** [CreaturePhil/Showdown-Boilerplate#65]
![Avatar exibition in profile don't work for offline users](http://i.imgur.com/Q7jHGZ7.png)

**Comment by CreaturePhil** [comment]
I can't interpret what you mean by that pictorially. Care to explain?

**Comment by DaniellMesquita** [comment]
An photo worth more than 1.000 words, but ok. As the title explain, I comment that Avatar exibition in profile don't work for offline users (only for users that is online).

**Comment by CreaturePhil** [comment]
You should have highlighted the avatar pic to make it more obvious :fearful:

**Comment by DaniellMesquita** [comment]
Yes, I've forgot ^^

**Comment by DaniellMesquita** [comment]
But this will have fix?

**Comment by DaniellMesquita** [comment]
Yes, I've forgot ^^
But this will have fix?
