### ISSUE TITLE
Proxy error in c9

### ISSUE THREAD

**Issue by Champ1604** [CreaturePhil/Showdown-Boilerplate#71]
I don't know but it's having some Proxy Error when it's used with Cloud9. It displays
"Request couldn't be proxied !"
On the localhost site.
Screenshot of it can be viewed [here.](http://prntscr.com/a0q18s)
I hope a solution comes out.

**Comment by TheFenderStory** [comment]
Looking at your screenshot, i'd double check that you have `exports.port = process.env.PORT`. If that doesn't work let me know and I wouldn't mind taking a look at the code for you. I wasn't able to replicate the issue in c9 myself.

**Comment by Champ1604** [comment]
Do I have to change this in config.js ? [(Screenshot)](http://prntscr.com/a1ywma)
If yes, it's showing another error.
It's showing a different type of error now.
Please help.
[Screenshot here.](http://prntscr.com/a1yx8n)

**Comment by TheFenderStory** [comment]
Are you sure you are connecting to the right url for your c9? There is a specific url associated with your workspace that can be found under the share tab in the top left.

**Comment by TheFenderStory** [comment]
If you'd like to get in touch with me directly, you can contact me on origin.psim.us and i could give you a hand directly if you'd like.

**Comment by Champ1604** [comment]
Finally succeeded in it. Found out my mistake. I didn't do it public. Better close this issue.
