### ISSUE TITLE
Problem with profile

### ISSUE THREAD

**Issue by Latios1** [CreaturePhil/Showdown-Boilerplate#73]
http://i.imgur.com/vjNnZJ0.png
Why?

**Comment by TheFenderStory** [comment]
Hard to say with the given information. The user in question could still be online on an alt. It also may not have updated at the time. Let me know if this user still appears to be online in profile and i'll see if i can help you out if you need more support.

**Comment by Latios1** [comment]
He was offline.
Why profile's last seen doesn't update?(Sorry for my english)

**Comment by Latios1** [comment]
?

**Comment by CreaturePhil** [comment]
@Latios1 He probably got dced and somehow didn't emit the socket.disconnect event so the seen wasn't able to record or his user object wasn't deleted yet so it show him as online.
