### ISSUE TITLE
Joining dice game makes you send the room name

### ISSUE THREAD

**Issue by megas4ever** [CreaturePhil/Showdown-Boilerplate#77]

**Comment by TheFenderStory** [comment]
Fixed in [377154a](https://github.com/TheFenderStory/Showdown-Boilerplate/commit/377154a1f4a6c3a9cffeba77431f86a5206e3ae0), as soon as Phil merges pr. Let me know if you find any other bugs.

**Comment by megas4ever** [comment]
Thanks!
